Restaurant/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^catering/', include('catering.urls', namespace='catering')),
    url(r'^menu/', include('menu.urls', namespace='menu')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import homeView


urlpatterns = [
    url(r'$', homeView.as_view(), name="home"),
]

menu/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import menuView, singleItem


urlpatterns = [
    url(r'^list/$', menuView.as_view(), name="menu"),
    url(r'^item/(?P<pk>[0-9]+)/$', singleItem.as_view(), name="single-item"),

]

menu/models.py
from django.db import models

# Create your models here.

menu/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import TemplateView
from product.models import Product, ProductCategory

class menuView(TemplateView):
    template_name = 'menu/index.html'

    def get_context_data(self, **kwargs):
        context = {}
        categories = ProductCategory.objects.all()
        products = Product.objects.filter(is_active=True)

        context['categories'] = categories
        context['products'] = products



        return context

class singleItem(generic.DetailView):
    template_name = 'menu/single.html'


    model = Product
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(singleItem, self).get_context_data(**kwargs)



        return context

menu/templates/menu/index.html
{%extends 'Restaurant/base/page-base.html'%}


{%block content%}
{%load static%}
 <!-- Page Header -->
            <section class="page_header" style="background: url('/static/img/header/menu.jpg') no-repeat center top;background-size: cover;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <h2 class="text-uppercase wow fadeInDown">Menu</h2>
                            <p class="wow fadeInUp">See what we have in our menu list</p>
                        </div>
                    </div>
                </div>
            </section>


            <!-- menu-->
            <section class="menu menu2">
                <div class="container">
                    <div class="food-menu wow fadeInUp">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="menu-tags4">
                                    <span data-filter="*" class="tagsort4-active">All</span>
                                    {%for cat in categories%}
                                    <span data-filter=".{{cat.name}}">{{cat.name}}</span>
                                    {%endfor%}
                                </div>
                            </div>
                        </div>
                        <div class="row menu-items4">
                            {%for product in products%}
                            <div class="menu-item4 col-sm-4 col-xs-12
                              {%for cat in product.productcategory.all%}
                              {{cat.name}}
                              {%endfor%}">
                                <div class="menu-info">
                                    {%for img in product.images.all%}
                                    {%if img.is_main %}
                                        <img src="/media/{{img.image}}" class="img-responsive" alt="" />
                                    {%endif%}

                                    {%endfor%}
                                    <a href="{%url 'menu:single-item' pk=product.id %}">
                                        <div class="menu4-overlay">
                                            <h4>{{product.name}}</h4>
                                            <p>{{product.short_description}}</p>
                                            <span class="price">${{product.price}}</span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            {%endfor%}

                        </div>
                    </div>
                </div>
            </section>



{%endblock%}

menu/templates/menu/single.html
{%extends 'Restaurant/base/page-base.html'%}


{%block content%}
{%load static%}
 <!-- Page Header -->
            <section class="page_header" style="background: url('/static/img/header/menu.jpg') no-repeat center top;background-size: cover;">

            </section>


            <!-- Shop Content -->
            <section class="shop-content" >
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="single-shop-carousel">
                                {%for img in product.images.all%}
                                <div>
                                    <img class="img-responsive" src="/media/{{img.image}}" alt="">
                                </div>
                                {%endfor%}
                            </div>
                            <div class="single-shop-carousel-nav">
                                {%for img in product.images.all%}
                                <div>
                                    <img class="img-responsive" src="/media/{{img.image}}" alt="">
                                </div>
                                {%endfor%}
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="col-md-6 shop-single-info">
                            <div class="shop-single-title">
                                <h3 class="text-left">{{product.name}}</h3>
                            </div>
                            <div class="shop-single-price">
                                <div class="ssp pull-left">${{product.price}}</div>
                            </div>
                            <p>{{product.short_description}}</p>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <!--<div class="shop-products">-->
                        <!--<h6>More Food Items</h6>-->
                        <!--<div class="row">-->
                            <!--<div class="col-md-3 col-sm-6">-->
                                <!--<div class="product-info">-->
                                    <!--<div class="product-img">-->
                                        <!--<img src="{% static 'img/shop/1.png' %}" alt="" />-->
                                    <!--</div>-->
                                    <!--<h4><a href="{%url 'menu:single-item' pk=product.id %}">Food Name</a></h4>-->
                                    <!--<div class="product-price">$100</div>-->
                                <!--</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->

                </div>
            </section>



{%endblock%}