Restaurant/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^catering/', include('catering.urls', namespace='catering')),
    url(r'^menu/', include('menu.urls', namespace='menu')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import aboutView


urlpatterns = [
    url(r'', aboutView.as_view(), name="about"),
]

catering/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import cateringView

urlpatterns = [
    url(r'', cateringView.as_view(), name="catering"),
]

contact/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import contactView


urlpatterns = [
    url(r'', contactView.as_view(), name="contact"),
]

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import homeView


urlpatterns = [
    url(r'$', homeView.as_view(), name="home"),
]

Restaurant/templates/Restaurant/base/footer.html
     {%load static%}
        <!-- Footer-->
            <section class="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-12">
                            <h1>About us</h1>
                            <p>Armenia is one of the oldest civilizations in the world with earliest mentions dating back to 2300 BC, the time when the legendary character “HAYK” established the Armenian nation at the crossroads between the Middle East, Europe and Asia. The capital city, Yerevan ...</p>
                            <a href="{%url 'about:about' %}">Read more &rarr;</a>
                        </div>

                        <div class="col-md-4  col-sm-6">

                        </div>


                        <div class="col-md-4  col-sm-6">
                            <h1>Reach us</h1>
                            <div class="footer-social-icons">
                                <a href="https://web.facebook.com/ararat17/" target="_blank">
                                    <i class="fa fa-facebook-square"></i>
                                </a>
                                <a href="https://www.yelp.com/biz/ararat-17-matthews-2" target="_blank">
                                    <i class="fa fa-yelp"></i>
                                </a>
                            </div>
                            <div class="footer-address">
                                <a href="https://www.google.com/maps/place/1361+Chestnut+Ln,+Matthews,+NC+28104/@35.0686092,-80.7031866,17z/data=!3m1!4b1!4m5!3m4!1s0x885425c84c07796d:0xf0b3897f8cddbca9!8m2!3d35.0686011!4d-80.7010178" target="_blank">
                                    <p><i class="fa fa-map-marker"></i>1361 Chestnut Lane, Matthews, North Carolina 28104</p>
                                </a>
                                <p><i class="fa fa-phone"></i>Phone: (704)-684-0107</p>
                                <p><i class="fa fa-envelope-o"></i>info@ararat17.com</p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Footer - Copyright -->
                <div class="footer-copyrights">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <p><i class="fa fa-copyright"></i> 2017. Ararat 17 .All rights reserved.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            </div>

        </div>
        <!-- Javascript -->
        <script src="{%static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script src="{%static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{%static 'js/vendor/jquery.flexslider-min.js' %}"></script>
        <script src="{%static 'js/vendor/spectragram.js' %}"></script>
        <script src="{%static 'js/vendor/owl.carousel.min.js' %}"></script>
        <script src="{%static 'js/vendor/velocity.min.js' %}"></script>
        <script src="{%static 'js/vendor/velocity.ui.min.js' %}"></script>
        <script src="{%static 'js/vendor/bootstrap-datepicker.min.js' %}"></script>
        <script src="{%static 'js/vendor/bootstrap-clockpicker.min.js' %}"></script>
        <script src="{%static 'js/vendor/jquery.magnific-popup.min.js' %}"></script>
        <script src="{%static 'js/vendor/isotope.pkgd.min.js' %}"></script>
        <script src="{%static 'js/vendor/slick.min.js' %}"></script>
        <script src="{%static 'js/vendor/wow.min.js' %}"></script>
        <script src="{%static 'js/animation.js' %}"></script>
        <script src="{%static 'js/vendor/vegas/vegas.min.js' %}"></script>
        <script src="{%static 'js/vendor/jquery.mb.YTPlayer.js' %}"></script>
        <script src="{%static 'js/vendor/jquery.stellar.js' %}"></script>
        <script src="{%static 'js/main.js' %}"></script>
        <script src="{%static 'js/vendor/mc/jquery.ketchup.all.min.js' %}"></script>
        <script src="{%static 'js/vendor/mc/main.js' %}"></script>
        <script src="{%static 'js/vendor/map.js' %}"></script>


     <script>
         $(document).ready(function(){
            $("#intro3 .home").vegas({
            slides: [
            {%for slide in slider %}
            {src: "/media/{{slide.image}}"},
            {%endfor%}
            ]
        });

         });
     </script>






</body>

</html>

Restaurant/templates/Restaurant/base/header.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
    <meta charset="utf-8">
    <title>Ararat 17 Restaurant</title>
    <meta name="author" content="Surjith S M">

    <!-- SEO -->
    <meta name="description" content="Ararat 17 Vegiterian Restaurant">
    <meta name="keywords" content="restaurant,cafe,food,NC,North Carolina,charlotte,Matthews">

    <!-- Favicons -->
    <link rel="shortcut icon" href="img/favicon.ico">

    <!-- Responsive Tag -->
    <meta name="viewport" content="width=device-width">

    <!-- CSS Files -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{%static 'css/plugin.css' %}">
    <link rel="stylesheet" href="{%static 'js/vendor/vegas/vegas.css' %}">
    <link rel="stylesheet" href="{%static 'css/main.css' %}">

    <!--[if lt IE 9]>
            <script src="{%static 'js/vendor/html5-3.6-respond-1.4.2.min.js' %}"></script>
        <![endif]-->
</head>

<body id="intro3" data-scroll-animation="true">
    <!--[if lt IE 8]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

    <!-- Preloder-->
    <div class="preloder animated">
        <div class="scoket">
            <img src="{%static 'img/preloader.svg' %}" alt="" />
        </div>
    </div>

    <div class="body">

        <!-- Navigation-->
        <nav class="navbar navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{%url 'home:home' %}">
                        <img src="{%static 'img/nav_logo.png' %}" alt="nav-logo">
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{%url 'home:home' %}">Home</a></li>
                        <li><a href="{%url 'about:about' %}">About</a></li>
                        <li><a href="{%url 'catering:catering' %}">Catering</a></li>
                        <li><a href="{%static 'pdf/menu.pdf'%}">Menu</a></li>
                        <li><a href="{%url 'contact:contact' %}">Contact</a></li>
                    </ul>
                </div>
                <!--/.navbar-collapse -->
            </div>
        </nav>

Restaurant/templates/Restaurant/base/no-slider.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Restaurant/templates/Restaurant/base/page-base.html
{% include 'Restaurant/base/header.html'%}


<!-- Slider Place -->


<!-- No Slider -->

{%block content%}


{%endblock%}














{% include 'Restaurant/base/footer.html'%}

Restaurant/templates/Restaurant/base/with-slider.html
{% include 'Restaurant/base/header.html'%}
{% include 'Restaurant/includes/slider.html'%}


<!-- Slider Place -->


<!-- No Slider -->

{%block content%}


{%endblock%}














{% include 'Restaurant/base/footer.html'%}